server:
  port: 8888
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  mvc:
    view:
      suffix: /
      prefix: .jsp
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
mybatis:
  type-aliases-package: com.baizhi.ysk.entity
  mapper-locations: classpath:com/baizhi/ysk/mapper/*Mapper.xml
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
  width: 150
  height: 150
  tracker-list: #TrackerList参数,支持多个
    - 192.168.169.135:22122